# Generated by Django 4.1.3 on 2022-11-22 21:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CORSRequestResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A more or less 'secondary' primary key to reference this DB object.",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time at which this record was created.",
                    ),
                ),
                (
                    "time_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The time at which this record was last updated.",
                    ),
                ),
                (
                    "host_domain",
                    models.TextField(
                        db_index=True,
                        help_text="The host domain that the CORS request result originated from.",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="The URL that was requested.", null=True
                    ),
                ),
                (
                    "url_domain",
                    models.TextField(
                        db_index=True,
                        help_text="The domain of the URL that was requested.",
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        help_text="The amount of time elapsed between request start and either response or error."
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        help_text="Whether or not the request was successful."
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Base64-encoded HTML content that was retrieved from the URL.",
                        null=True,
                    ),
                ),
                (
                    "err_msg",
                    models.TextField(
                        blank=True,
                        help_text="A string denoting the type of error that was observed when a fetch was attempted of the URL.",
                        null=True,
                    ),
                ),
                (
                    "err_location",
                    models.TextField(
                        blank=True,
                        help_text="The location where the error was thrown (if an error was thrown).",
                        null=True,
                    ),
                ),
                (
                    "client_meta",
                    models.JSONField(
                        blank=True,
                        help_text="A blob of metadata describing the client that we received the request from.",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HostDomain",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A more or less 'secondary' primary key to reference this DB object.",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time at which this record was created.",
                    ),
                ),
                (
                    "time_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The time at which this record was last updated.",
                    ),
                ),
                (
                    "domain",
                    models.TextField(
                        db_index=True,
                        help_text="The domain we expect to receive HTTP requests to.",
                        unique=True,
                    ),
                ),
                (
                    "redirect_domain",
                    models.TextField(
                        help_text="The domain that should be redirected to when a request is received to this host domain."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScanSummary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A more or less 'secondary' primary key to reference this DB object.",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time at which this record was created.",
                    ),
                ),
                (
                    "time_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The time at which this record was last updated.",
                    ),
                ),
                (
                    "parent_domain",
                    models.TextField(
                        db_index=True,
                        help_text="The parent domain that was used to start the scan.",
                    ),
                ),
                (
                    "subdomains_count",
                    models.IntegerField(
                        help_text="The number of subdomains that were discovered."
                    ),
                ),
                (
                    "https_subdomains_count",
                    models.IntegerField(
                        help_text="The number of subdomains that were discovered to have HTTPS available / enabled."
                    ),
                ),
                (
                    "time_started",
                    models.DateTimeField(
                        help_text="The time at which the scan started."
                    ),
                ),
                (
                    "time_completed",
                    models.DateTimeField(help_text="The time at which the scan ended."),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TargetDomain",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A more or less 'secondary' primary key to reference this DB object.",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time at which this record was created.",
                    ),
                ),
                (
                    "time_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The time at which this record was last updated.",
                    ),
                ),
                (
                    "domain",
                    models.TextField(
                        db_index=True,
                        help_text="The parent domain that was used to start the scan.",
                        unique=True,
                    ),
                ),
                (
                    "last_scan_guid",
                    models.UUIDField(
                        db_index=True,
                        help_text="A UUID for identifying the most recent subdomains identified for this target.",
                    ),
                ),
                (
                    "time_last_scan_set",
                    models.DateTimeField(
                        help_text="The most recent time at which 'last_scan_guid' was set."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScanDomain",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A more or less 'secondary' primary key to reference this DB object.",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time at which this record was created.",
                    ),
                ),
                (
                    "time_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The time at which this record was last updated.",
                    ),
                ),
                (
                    "domain",
                    models.TextField(
                        db_index=True, help_text="The domain that was discovered."
                    ),
                ),
                (
                    "has_https",
                    models.BooleanField(
                        help_text="Whether or not this domain had an HTTP services available / enabled."
                    ),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        blank=True,
                        help_text="The scan where this domain was identified.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.scansummary",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HostToTargetMapping",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A more or less 'secondary' primary key to reference this DB object.",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time at which this record was created.",
                    ),
                ),
                (
                    "time_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The time at which this record was last updated.",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether or not this mapping should be considered active.",
                    ),
                ),
                (
                    "host_domain",
                    models.ForeignKey(
                        blank=True,
                        help_text="The host domain side of the mapping.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.hostdomain",
                    ),
                ),
                (
                    "target_domain",
                    models.ForeignKey(
                        blank=True,
                        help_text="The target domain side of the mapping.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.targetdomain",
                    ),
                ),
            ],
            options={
                "unique_together": {("host_domain", "target_domain")},
            },
        ),
        migrations.AddField(
            model_name="hostdomain",
            name="targets",
            field=models.ManyToManyField(
                related_name="hosts",
                through="web.HostToTargetMapping",
                to="web.targetdomain",
            ),
        ),
        migrations.CreateModel(
            name="TargetSubdomain",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A more or less 'secondary' primary key to reference this DB object.",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time at which this record was created.",
                    ),
                ),
                (
                    "time_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The time at which this record was last updated.",
                    ),
                ),
                (
                    "domain",
                    models.TextField(
                        db_index=True,
                        help_text="The subdomain to use in payload generation for the parent target.",
                    ),
                ),
                (
                    "scan_guid",
                    models.UUIDField(
                        help_text="The scan batch GUID from the target domain wherein this subdomain was added."
                    ),
                ),
                (
                    "target_domain",
                    models.ForeignKey(
                        blank=True,
                        help_text="The parent domain that this subdomain is being targeted under.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.targetdomain",
                    ),
                ),
            ],
            options={
                "unique_together": {("domain", "scan_guid")},
            },
        ),
    ]
