# Generated by Django 4.1.3 on 2022-11-22 03:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CORSRequestResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A more or less 'secondary' primary key to reference this DB object.",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time at which this record was created.",
                    ),
                ),
                (
                    "time_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The time at which this record was last updated.",
                    ),
                ),
                (
                    "host_domain",
                    models.TextField(
                        db_index=True,
                        help_text="The host domain that the CORS request result originated from.",
                    ),
                ),
                ("url", models.URLField(help_text="The URL that was requested.")),
                (
                    "url_domain",
                    models.TextField(
                        db_index=True,
                        help_text="The domain of the URL that was requested.",
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        help_text="The amount of time elapsed between request start and either response or error."
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        help_text="Whether or not the request was successful."
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Base64-encoded HTML content that was retrieved from the URL.",
                        null=True,
                    ),
                ),
                (
                    "err_msg",
                    models.TextField(
                        blank=True,
                        help_text="A string denoting the type of error that was observed when a fetch was attempted of the URL.",
                        null=True,
                    ),
                ),
                (
                    "client_meta",
                    models.JSONField(
                        blank=True,
                        help_text="A blob of metadata describing the client that we received the request from.",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
